// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cn.test.userservice.v1.proto

package cn.test.userservice.v1;

public interface RequestDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.test.userservice.v1.RequestData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
