// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cn.test.userservice.v1.proto

package cn.test.userservice.v1;

public interface ResponseDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.test.userservice.v1.ResponseData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
